import logging

# PWM
PWM_ADDRESS = 0x40
PWM_FREQUENCY = 60
PWM_DISTANCE_SERVO_CHANNEL = 0
PWM_LEFT_MOTOR_SPEED_CHANNEL = 2
PWM_RIGHT_MOTOR_SPEED_CHANNEL = 1

SERVO_ON = True
SERVO_MAX = 560
SERVO_MIN = 160
SERVO_HALF = 355
STEP_POS = [160, 250, 355, 460, 560]

DISTANCE_THRESHOLD = 25
SIDE_DISTANCE_THRESHOLD = 15
TIME_SINCE_LAST_TURN_THRESHOLD = 3

SAMPLE_SIZE = 4
SAMPLE_WAIT = 0.02

DEFAULT_SPEED_MPM = 15
DEFAULT_SPEED = 60
ROTATE_SPEED = 90

ROTATE_TIME = 0.7
BACKWARD_TIME = 0.5

# sensor1
TRIG = 23
ECHO = 24

# motor1
RIGHT_MOTOR_FORWARD = 17
RIGHT_MOTOR_BACKWARD = 18
RIGHT_MOTOR_ENCODER = 27

# motor2
LEFT_MOTOR_FORWARD = 12
LEFT_MOTOR_BACKWARD = 16
LEFT_MOTOR_ENCODER = 22

WHEEL_MOVEMENT_STUCK_TIME = 3
WHEEL_MOVEMENT_STUCK_THRESHOLD = 3000

PULSE_PER_METER = 78.75

LOG_LEVEL = logging.DEBUG
LOG_PATH = "/var/log/wirus.log"
LOG_FORMAT = "%(levelname)s %(asctime)s %(message)s"

CHATTINESS = 1
